version: "3.8"

services:
  api-server:
    image: covector/quecat:api
    ports:
      - 4915:4915
    volumes:
      - ./local-storage:/local-storage
  web-server:
    image: covector/quecat:webpage
    ports:
      - 3000:3000
