version: "3.8"

services:
  api:
    image: quecat-api
    ports:
      - 4915:4915
    volumes:
      - ./local-storage:/local-storage
  web-server:
    image: quecat-webpage
    ports:
      - 3000:3000